### ISSUE TITLE
Issue With Users Sending Friend Requests to Each Other Still Happens

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#102]
From the latest version, Issue #99 is still happening

**Comment by lvcodes3** [comment]
Can you provide more clarification or exact step by step examples? On my computer User1 is not able to send User2 a friend request if User1 already has a friend request from User2 or vice versa.

**Comment by Jaspinder00** [comment]
I'm using Chrome as my web browser, and if User 1 sends a friend request to User 2, User 2 is still able to send a friend request to user A:
![Screenshot 2022-11-21 170719](https://user-images.githubusercontent.com/113147505/203189924-7738ffed-d7e7-40db-8d5a-bf59046dcd58.png)

And then when either user accepts, the other user is still able to accept:
![Screenshot 2022-11-21 170804](https://user-images.githubusercontent.com/113147505/203189935-a09095f6-60d0-437c-86c8-fca9a3b5e682.png)

It might be something to do with merging in Github. I'll look more into this and add another comment here if I find what exactly the issue is.
