### ISSUE TITLE
Username Length Inconsistency Between Frontend and Backend

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#104]
In commits b92c0df52c82f58bee823762cbd3d97293c456b6 and 1eb840e58c7335239dd8c0d68f924e0ed3c78f92, line 111 was changed to require usernames to be less than 30 characters, but in the frontend, it allows users to input 32 characters, but only allows edits to be made for <=30 characters. So, line 111 should be changed to 32.

Also, in the same file in line 112, it says that users should be allowed to have one character usernames, but I can only have usernames be 2 or more characters.

**Comment by lvcodes3** [comment]
Solved, check pull request for explanation.
