### ISSUE TITLE
Users Can Delete Leagues by Commenting on Them and Then Deleting Their Account

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#106]
From my testing, commit 258bca2920ff3e964331013c5daf70e92132a09a seems to have fixed users that join a league and delete their account. But as mentioned in Issue #93, users can still just leave a comment on a league and delete their account to make the league appear blank to everyone.

To reproduce:
1. Have User A create a league
2. User B comments or replies on that league
3. User B deletes their account
4. The league created by User A appears blank to everyone

**Comment by lvcodes3** [comment]
In progress.

**Comment by lvcodes3** [comment]
Solved, once merged into the branch please test extensively to make sure I didn't miss anything, thanks.
