### ISSUE TITLE
Possible Fix for Friend Requests Between Two Users

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#117]
In Issue #102, I reported that the issue with friends sending a friend request to each other and possibly being added twice in a friend list was still happening for me. In the users.js file in the routes folder, adding the line `const user = await User.findById(req.user._id);` before line 456, which is `if (req.user.friendRequests.includes(req.body.friendcode)) {` and removing the 'req.' part from line 456 seems to fix this problem for me. The new piece of code should look like:

![Screenshot 2022-11-23 094852](https://user-images.githubusercontent.com/113147505/203615476-b544053b-f161-4925-8154-fee44d857a2b.png)

@lvcodes3 can you check if adding this still works for you and make a pull request for it?

**Comment by lvcodes3** [comment]
Solved, I have reorganized parts of the code and also took into account your suggestions. New code works fine for me, let me know once you get the new code if it works. Thanks.
