### ISSUE TITLE
Users Can Select Zero, Negative, and Empty Stock Amounts

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#120]
**Description**
Users are allowed to create leagues with invalid stock quantities, which can mess with the game logic. Users can't select 0 and negative numbers from the arrows, but they can manually type those numbers in.

**To Reproduce**
1. Go to the Create League page and input the title and start and end dates.
2. Pick a valid ticker from the drop-down box
Now, either:
3a. Type in a zero or negative integer in the quantity box, and press 'Pick' and then 'Create League'
4a. League is created successfully, but game logic may not work as expected
or:
3b. Remove the quantity (making the text box empty), and press 'Pick' and then 'Create League'
4b. Backend crashes

**Expected Behavior**
Users should be forced to input an actual number greater than zero when selecting stock quantity.

**Actual Behavior**
Users are able to join leagues with zero or negative stock quantities; Backend crashes when users don't input a stock quantity and try to join.

**Screenshots**
With zero and negative stocks:
![Screenshot 2022-11-23 133025](https://user-images.githubusercontent.com/113147505/203655283-50aa355e-f1d5-4080-8c69-571e30074384.png)

With no input for quantity:
![Screenshot 2022-11-23 142000](https://user-images.githubusercontent.com/113147505/203655660-078b7117-e129-4e5b-bd2f-9d25ea227720.png)

**Comment by lvcodes3** [comment]
Solved.
