### ISSUE TITLE
Users Can Comment and Reply on Leagues They Did Not Join

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#122]
**Description**
If a user is not joined in a league, they are still allowed to comment and reply on that league. If they comment on the league and delete their account, the league appears blank to all users. If they reply on the league, any user trying to view the league will be redirected to a blank page until they refresh the league.

If a user is joined in a league, everything is handled properly since their account, comments, and replies are removed. But if the user is not joined in the league, problems can occur.

**To reproduce**
1. Have User A create a valid league
2. User B, who is not a part of that league created by User A, leaves a comment on User B's league page
3. User B deletes their account
4. The league appears blank to everyone else

**Expected Behavior**
Users that are not joined in a league should not be allowed to comment or reply in the league to prevent problems when they delete their account.

**Actual Behavior**
User not in a league leaving a comment makes the league appear blank to everyone. Them leaving a reply makes the league page blank for a user when they expand the related reply menu.

**Comment by lvcodes3** [comment]
Solved.
