### ISSUE TITLE
Frontend: Character Limit Not Set for Comments, Edits, and Replies

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#124]
**Description**
Users can enter more characters for comments, edits, and replies than they are actually able to post.

**Steps to Reproduce**
1. Create a League
2. Try to comment on the league with a text input greater than 200 characters

**Expected Behavior**
Text inputs for comment, edit comment, and reply to comment should have a 200 character limit to be consistent with the backend.

**Actual Behavior**
If a user enters a comment, edit, or reply greater than 200 characters, their comment will not be posted.

**Comment by mnosov622** [comment]
Hi @Jaspinder00 !

I would love to work on this issue. Could you assign it to me, please  ?
