### ISSUE TITLE
Users Can Enter a Space Character to Have Empty Names or Comments

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#125]
**Description**
Users can enter one or more space characters to have have unreadable names or comments.

**Steps to reproduce**
1. Go to either User Profile, Create League, or an Existing League's page.
2. Change username, bio, league name, comment, or reply to a space (' ') character

**Expected Result**
If the first character of a name or comment is a space character, then edits, names, or comments should not be accepted.

**Actual Result**
Users, Leagues, or comments having a space character as their name can make them appear invisible, making it harder to view them through the search feature or through the friends page.

**Comment by lvcodes3** [comment]
Solved.
