### ISSUE TITLE
Lowercase Stock Tickers Are Treated as Invalid Stocks

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#126]
**Description**
When creating or joining a league, if a user manually types in a stock ticker in lowercase letters, the stock is treated as invalid and the league cannot be created or joined into by the user.

**Steps to Reproduce**
1. Navigate to the 'Create League' page or an existing league's page
2. Enter a valid stock's ticker symbol in lowercase letters (i.e., aapl) and click the 'Pick' button
3. Click the 'Create League' or 'Join League' button

**Expected Result**
The backend should automatically convert the chosen stocks by the user to have all uppercase letters in order to properly handle possible inputs with different capitalizations by the user.

**Actual Result**
User is unable to join a league if they enter a valid stock ticker with incorrect capitalization.

**Comment by lvcodes3** [comment]
Solved.
