### ISSUE TITLE
Search and Profile Picture UI window scaling issue

### ISSUE THREAD

**Issue by 19quan** [JonahLozano/FS-CSCI150-F22-Team3#16]
At smaller window sizes, the search button and user profile picture will be misaligned.

![alignment](https://user-images.githubusercontent.com/99855082/193948157-dfc7156c-f04b-4d90-bd26-9196710cde22.PNG)

**Comment by JonahLozano** [comment]
Fixed in ed6b4e09a18d7a1bf6a1d0674eec0e2a8830ef0b
