### ISSUE TITLE
Error Message Not Displayed When Exceeding the Character Limit on Username or Bio

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#28]
While editing a user profile, if a user tries to enter a username containing more than 32 characters or a bio containing more than 300 characters, users won't know why changes can't be made.

**Comment by RJMawi** [comment]
Fixed by adding maxlength attribute to #editProfileName and #editProfileBio and added spans to prime users with those limits
