### ISSUE TITLE
League Dates Are Not Restricted

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#32]
Users are able to create leagues dated before the day of the league's creation. It is also possible to select end date before the selected start date.

Ex:
![Screenshot 2022-10-30 145124](https://user-images.githubusercontent.com/113147505/198903320-23d047fe-7d23-4921-8196-4ac47953d452.png)

This league was created on 2022-10-30, but it can be selected to start at 2022-10-18 and end at 2022-09-29.  There should be restrictions implemented to prevent this.

**Comment by lvcodes3** [comment]
solved.
