### ISSUE TITLE
A User Can Be Added as a Friend Multiple Times at the Backend

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#34]
If you go to the friends page, input the friend code, and click the "Add Friend" button, you can keep clicking it. This will add the same user id into the friends list in the backend, but the added friend will only show once in the frontend.

Ex:
![Screenshot_20221030_052931](https://user-images.githubusercontent.com/113147505/198909911-d24a5efe-11a1-4569-82e0-1a73eb059bc3.png)

The friends list contains the same id 10 times because I clicked the add friend button 10 times.

**Comment by lvcodes3** [comment]
This is the same issue as #57, solved now.
