### ISSUE TITLE
Users can add themselves as friends

### ISSUE THREAD

**Issue by 19quan** [JonahLozano/FS-CSCI150-F22-Team3#40]
![image](https://user-images.githubusercontent.com/99855082/199361616-44ee2733-7fbf-4db8-be66-84ed6bd061cb.png)

**Comment by 19quan** [comment]
If a user inputs their own friend code, they will add themselves as a friend.

**Comment by 19quan** [comment]
Users can still request to add themselves. After accepting the friend request the website will crash; restarting the website will have the user added as a friend and as a request simultaneously.
![friends](https://user-images.githubusercontent.com/99855082/199851357-85de31c0-de80-49e8-9a9c-8a222f14c2e0.PNG)

**Comment by lvcodes3** [comment]
solved.
