### ISSUE TITLE
Users Can Send Multiple Friend Requests to the Same User

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#57]
Users can repeatedly send friend requests to another user, which can take up a lot of space in a users friend request box.

![Screenshot 2022-11-08 155441](https://user-images.githubusercontent.com/113147505/200701695-6938b2b5-35f8-4e19-9cda-174d9810a6f5.png)

**Comment by lvcodes3** [comment]
This is the same issue as #34, solved now.
