### ISSUE TITLE
Players Can Search for and Join Leagues After the Respective End Dates

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#59]
To reproduce, log-in to a different account that is not already joined in the passed league. Then, search for a league that has passed its end date. It will allow the user to join the league and have access to all the features as if the league is still active. Ideally, passed leagues should not be able to be searched for or joinable and should become "view-only" to all users.

**Comment by lvcodes3** [comment]
Solved.
