### ISSUE TITLE
Leagues Move to the “Passed Leagues” Section Before They Are Supposed to Start

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#60]
To reproduce, simply create a league, and the league will move to the "Passed Leagues" section at 4PM on the day before it is supposed to start. For example, on 11/13 before 4PM, I created a league that should start on 11/14 and end on 11/15. On the "League" page, it was in the "Active Leagues" section, but at 4PM on 11/13, it moved to the "Passed Leagues" section when it should be considered as active.

**Comment by lvcodes3** [comment]
Passed tests on my end, but testers should double check to see if it is working properly.
