### ISSUE TITLE
Users Can Send Friend Requests to Other Users That They Are Already Friends With

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#63]
Users can no longer have multiple outgoing friend requests at the same time, however, they are still able to send a friend request to an already existing friend.

To reproduce: 
1. Send another user a friend request. 
2. That user accepts the friend request and now both users are friends.
3. You are now able to send another friend request to that same user.

![Screenshot 2022-11-14 172128](https://user-images.githubusercontent.com/113147505/201803400-392d3eb8-f11c-429a-a4c8-44d34e88d40f.png)

**Comment by lvcodes3** [comment]
Solved.
