### ISSUE TITLE
“Friends” Page Becomes Unusable if a Friend Deletes Their Account

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#66]
Description:
If a friend of a user deletes their own account, then the user is no longer able to access their own friends page. It appears completely blank.

Steps to Reproduce:
1. Log-in to an account (User A).
2. Add another account (User B) as a friend.
3. User B accepts the friend request.
4. If User A deletes their account, User B is no longer able to access the "friends" page and vice versa.

Expected Behavior: A friend who deletes their account should be removed from all users' friend lists.
Actual Behavior: A friend who deletes their account causes the users they were friends with to be unable to access the "friends" page.

**Comment by lvcodes3** [comment]
Solved.
