### ISSUE TITLE
Frontend: Bio doesn't wrap propperly

### ISSUE THREAD

**Issue by JonahLozano** [JonahLozano/FS-CSCI150-F22-Team3#71]
<img width="1251" alt="c053f15c0db7ec48a37931f5c1c5240a" src="https://user-images.githubusercontent.com/111929937/202280527-fbca6dd9-cc26-4b5a-9cca-19f4a14c85a6.png">

**Comment by RJMawi** [comment]
Fixed by adding a max-width property to #profileBio's paragraph, along with word-wrap and white-space properties
