### ISSUE TITLE
Frontend: Bio edit box does not wrap propperly

### ISSUE THREAD

**Issue by JonahLozano** [JonahLozano/FS-CSCI150-F22-Team3#72]
<img width="998" alt="7f328c02d2ad362776c5a6f4942b848f" src="https://user-images.githubusercontent.com/111929937/202281264-2e5ddcc8-55f7-41e7-bc3d-97a59957b8d5.png">

**Comment by RJMawi** [comment]
Fixed by adding a max-width property to #editProfileBio's textarea, along with word-wrap and white-space properties
