### ISSUE TITLE
Frontend: Inconsistent margin/gap between cards across the website

### ISSUE THREAD

**Issue by JonahLozano** [JonahLozano/FS-CSCI150-F22-Team3#81]
![a362833c864555b1931f08c0df8a0155](https://user-images.githubusercontent.com/111929937/202586622-841de3bd-1517-4643-a323-126a360f49f6.png)
![1f23fbf47e03f6177d96241c431886e2](https://user-images.githubusercontent.com/111929937/202586629-7857b241-8322-4e14-8413-33aded8c1a12.png)
![ecaa66bacce677d34ee977338e062b1e](https://user-images.githubusercontent.com/111929937/202586639-7e0f63f1-aac5-4785-b897-860aa60a4bf1.jpg)

**Comment by RJMawi** [comment]
Fixed; Store cards did not have a margin before and one has been added consistent with Stocks and Home cards
