### ISSUE TITLE
Deleting an Account Involved in a League Makes the League Appear Blank to Everyone

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#93]
To Reproduce:
1. Create a League
2. Either:
    - Delete your account
    or
    - From a second account join the league or even just leave a comment and then delete that second account
3. The league can still be searched for, but if anyone tries to view it, the league's page appears completely blank

**Comment by lvcodes3** [comment]
Solved.
