### ISSUE TITLE
There Are Still Issues When Trying to Join a League by Entering Invalid Tickers

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#94]
From Issue #90, the backend no longer crashes when trying to join with an invalid stock ticker. However, if a user tries to join the league with an invalid ticker, it doesn't allow them to join the league, but it still moves the league to their 'Active Leagues' section. But, it doesn't list that user in the league along with the other users, and it doesn't allow them to join the league at this point even if they enter valid stocks.

**Comment by lvcodes3** [comment]
Solved.
