### ISSUE TITLE
Can No Longer Add Friends by Their ID

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#96]
Users can no longer add friends. From commit bd3ace1ed04fc1fcf22cfc26f457b51c9d64cf2e, line 190 `req.body.friendcode.length !== 32 || // friendcode input must be 32 chars` should be changed from 32 to 24 because my accounts are displaying 24 characters for the user ID.

**Comment by lvcodes3** [comment]
Solved.
