### ISSUE TITLE
Users Can Send Friend Requests to Each Other

### ISSUE THREAD

**Issue by Jaspinder00** [JonahLozano/FS-CSCI150-F22-Team3#99]
Users are able to send friend requests to each other:
![Screenshot 2022-11-19 114619](https://user-images.githubusercontent.com/113147505/202868788-36ce74c5-be7a-4c0b-9057-ecfd3faa0e4c.png)

If both users accept, they are added twice to both friend lists:
![Screenshot 2022-11-19 114643](https://user-images.githubusercontent.com/113147505/202868792-cf97344f-9a01-4ba2-adb1-3f4c22e2c012.png)

**Comment by lvcodes3** [comment]
Solved.
